# Generated by Django 4.1.4 on 2023-01-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_name_set', to='webv1.category')),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catid_set', to='webv1.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catid_set', to='webv1.categorytype'),
        ),
        migrations.AddField(
            model_name='category',
            name='catid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_type_set', to='webv1.categorytype'),
        ),
    ]
