# Generated by Django 4.1.4 on 2023-02-01 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriestb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=250)),
                ('category_name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'categoriestb_new',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category_typetb',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'category_typetb_new',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(max_length=30)),
                ('parent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_like', models.JSONField()),
                ('user_seen', models.IntegerField()),
                ('user_setting', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('ent_id', models.AutoField(primary_key=True, serialize=False)),
                ('ent_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=100)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webv1.category')),
            ],
        ),
    ]
