# Generated by Django 4.1.4 on 2023-05-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'client_register_table',
            },
        ),
        migrations.CreateModel(
            name='VilniusEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('image_src', models.TextField(null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('working_hours', models.TextField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('rating', models.CharField(max_length=10, null=True)),
                ('latitude', models.CharField(max_length=30, null=True)),
                ('longitude', models.CharField(max_length=30, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webv1.category')),
            ],
            options={
                'db_table': 'vilnius_events_2',
            },
        ),
        migrations.CreateModel(
            name='UserLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entertainment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webv1.vilniusevents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webv1.userregister')),
            ],
            options={
                'db_table': 'user_liked',
            },
        ),
    ]
