# Generated by Django 4.1.4 on 2023-05-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
