# Generated by Django 4.1.4 on 2023-05-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientlogin',
            options={'managed': True},
        ),
    ]
