# Generated by Django 4.1.4 on 2023-03-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0002_pamatyklietuvoje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pamatyklietuvoje',
            options={'managed': False},
        ),
    ]
