# Generated by Django 4.1.4 on 2023-05-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0002_alter_clientlogin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientlogin',
            options={'managed': False},
        ),
    ]
