# Generated by Django 4.1.4 on 2023-05-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0002_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='likes',
            table='client_likes_table',
        ),
        migrations.AlterModelTable(
            name='userlogin',
            table='client_login_table',
        ),
        migrations.AlterModelTable(
            name='userregister',
            table='client_register_table',
        ),
        migrations.AlterModelTable(
            name='vilniusevents',
            table='vilnius_events',
        ),
    ]
