# Generated by Django 4.1.4 on 2023-05-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0002_alter_vilniusevents_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userliked',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vilniusevents',
            options={'managed': True},
        ),
    ]
