# Generated by Django 4.1.4 on 2023-05-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0003_alter_likes_table_alter_userlogin_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entertainment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webv1.vilniusevents')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webv1.userregister')),
            ],
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
