# Generated by Django 4.1.4 on 2023-04-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0003_alter_pamatyklietuvoje_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogIn',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='pamatyklietuvoje',
            table='pamatyk_Lietuvoje',
        ),
    ]
