# Generated by Django 4.1.4 on 2023-05-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0003_alter_userliked_options_alter_vilniusevents_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userliked',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vilniusevents',
            options={},
        ),
        migrations.AlterField(
            model_name='userliked',
            name='entertainment',
            field=models.ForeignKey(db_column='entertainment_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='webv1.vilniusevents'),
        ),
    ]
