# Generated by Django 4.1.4 on 2023-05-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0003_alter_clientlogin_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientlogin',
            table='client_login_table',
        ),
    ]
