# Generated by Django 4.1.4 on 2023-05-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0004_alter_clientlogin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userregister',
            table='client_register_table',
        ),
    ]
