# Generated by Django 4.1.4 on 2023-05-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0004_userlogin_alter_pamatyklietuvoje_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_register',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VilniusEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image_src', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'vilnius_events',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='userlogin',
            table='user_login',
        ),
    ]
