# Generated by Django 4.1.4 on 2023-05-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0004_userliked_delete_likes_delete_userlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userliked',
            old_name='entertainment_id',
            new_name='entertainment',
        ),
        migrations.RenameField(
            model_name='userliked',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterModelTable(
            name='userliked',
            table='userliked',
        ),
    ]
