# Generated by Django 4.1.4 on 2023-05-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0005_userregister_vilniusevents_alter_userlogin_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PamatykLietuvoje',
        ),
    ]
