# Generated by Django 4.1.4 on 2023-05-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0005_alter_userregister_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientLogin',
        ),
        migrations.AlterModelTable(
            name='likes',
            table='client_likes_table',
        ),
        migrations.AlterModelTable(
            name='userlogin',
            table='client_login_table',
        ),
    ]
