# Generated by Django 4.1.4 on 2023-05-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0005_rename_entertainment_id_userliked_entertainment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userliked',
            table='user_liked',
        ),
    ]
