# Generated by Django 4.1.4 on 2023-05-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0006_alter_userliked_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vilniusevents',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
