# Generated by Django 4.1.4 on 2023-05-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0006_delete_pamatyklietuvoje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
    ]
