# Generated by Django 4.1.4 on 2023-05-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0007_alter_vilniusevents_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vilniusevents',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vilniusevents',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vilniusevents',
            name='working_hours',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
