# Generated by Django 4.1.4 on 2023-05-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0007_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_id_list', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
