# Generated by Django 4.1.4 on 2023-05-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0008_likes_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'managed': False},
        ),
    ]
