# Generated by Django 4.1.4 on 2023-05-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0008_alter_vilniusevents_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vilniusevents',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vilniusevents',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vilniusevents',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vilniusevents',
            name='image_src',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vilniusevents',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
