# Generated by Django 4.1.4 on 2023-05-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webv1', '0009_alter_likes_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='likes',
            table='clientLikes',
        ),
    ]
